config/routes.rb
Rails.application.routes.draw do
  get "/login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "/logout", to: "user_sessions#destroy"

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :user_groups
  has_many :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  attr_accessor :password_confirmation

  has_many :groups, through: :user_groups
  has_many :messages

  validates :email, presence: true, uniqueness: true
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :require_login

  def require_login
    unless logged_in?
      redirect_to login_path
    end
  end

  def not_authenticated
    redirect_to login_path
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def new
  end
  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_to users_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  def index
    @users = User.all
  end
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to 
    else
      render :new
    end
  end
end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Message App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <!-- Enable PWA manifest for installable apps -->
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

    <!-- Includes all stylesheet files in app/assets/stylesheets -->
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header>
      <nav class='navbar navbar-expand-lg navigation navbar-light bg-light'>
        <div class="container">
          <ul class='navbar-nav ms-auto align-items-center'>
            <li class='nav-item dropdown'>
              <% if logged_in? %>
                <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete } %>
                <%= link_to "ユーザー一覧", users_path %>
              <% else %>
                <%= link_to "ログイン", login_path %>
                <%= link_to "ユーザー登録", new_user_path %>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/user_sessions/new.html.erb
<div class="container mt-5">
  <div class="container mt-5">
    <div class="card mx-auto" style="max-width: 500px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
      <h4 class="mb-0">ログイン画面</h4>
      <div class="card-body">
        <%= form_with(url: login_path, class: "needs-validation") do |form| %>
          <div class="mb-3">
            <%= form.label :email, class: "form-label" %>
            <%= form.text_field :email, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.label :password, class: "form-label" %>
            <%= form.password_field :password, class: "form-control" %>
          </div>
          <div class="mb-3">
            <%= form.submit "ログイン" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container text-center">
<h1>ユーザー一覧</h1>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
       <tr>
          <th> name </th>
          <th> email </th>
       </tr>
     </thead>
     <% @users.each do |user| %>
       <tr>
         <td><%= user.name %></td>
         <td><%= user.email %></td>
       </tr>
<% end %>

app/views/users/new.html.erb
<br>
<br>
<div class="card mx-auto" style="max-width: 500px; box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.1);">
  <h4 class="mb-0">ユーザー登録</h4>
  <div class="card-body">
    <%= form_with(model:@user, class: "needs-validation") do |form| %>
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :email, class: "form-label" %>
        <%= form.text_field :email, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.label :password_confirmation, class: "form-label" %>
        <%= form.password_field :password_confirmation, class: "form-control" %>
      </div>
      <div class="mb-3">
        <%= form.submit "登録" %>
      </div>
    <% end %>
  </div>
</div>